spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 19970612
    url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8


server:
  port: 8081
